host: "localhost"
port: 8000

utils:
  ImageHandler:
    chunk_size: 4096

dev:
  name: "dev"
  auth:
    timedelta: 86400
    secret_key: "somesectretkeys"
    algorithm: "HS256"
  dirs:
    root: "/"
    images: "images/"
  secure_cookies_by_default: False
  database:
    sqlite:
      name: "imageapi.db"
      connection_string: "sqlite://{dev.dirs.root}{dev.database.sqlite.name}"
test:
  name: "test"
  auth:
    timedelta: 86400
    secret_key: "somesectretkeys"
    algorithm: "HS256"
  secure_cookies_by_default: False
  dirs:
    root: "/"
    images: "{test.dirs.root}images/"
  database:
    sqlite:
      name: "test.db"
      connection_string: "sqlite://{test.dirs.root}{test.database.sqlite.name}"
